### PR TITLE
Cache locales

### PR DESCRIPTION
**Pull request by alexanderweiss**
Cache locales, so that only one query per locale per model is required instead of each time a translation is requested through e.g. translate.

It may be optimised further by caching these locales in the Translator class for example. That way they can be shared between models. I found that somewhat complex though (because then it should probably be using a facade).

### CODE REVIEW

**Comment by vinkla** [comment]
I'll try this out and then get back to you. Question about the variable, why did you make it static?

**Comment by alexanderweiss** [comment]
If it weren't static it wouldn't be shared between the instances of models. That's the main goal.
Because right now, every model instance queries the database for locales; for example showing 10 translated items in say English means 1 query to retrieve them, 10 queries for the locales and 10 queries for the translations. This brings it down to 1 + 1 + 10.

**Comment by vinkla** [comment]
Okay, so with this setup it would be 1 + 1 + 1 instead?

**Comment by alexanderweiss** [comment]
Uhm, no.
Currently (master) it's 1 + 10 + 10 (getting items, getting locale, getting translations).
With this commit it becomes 1 + 1 + 10 (getting items, getting locale, getting translations).
I'd love to get it to 1 + 1 + 1, but that's more complex (that's what https://github.com/vinkla/translator/issues/29 is about)

**Comment by vinkla** [comment]
Aah okay, sorry. Read it through to fast. I'll try it out and come back to you.

**Comment by vinkla** [comment]
Just tested and it works fine. Thanks!

**Comment by alexanderweiss** [comment]
Thanks!

**Comment by vinkla** [comment]
No, thank you for helping out! Really appreciate it :)

**Pull request merged**
