### PR TITLE
revert to current used locale

### PR DESCRIPTION
**Pull request by schelmo**
see #59

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks for creating a pull request. Why are you setting the locale twice?

**Comment by vinkla** [comment]
Please add a test case for this to point out the issue.

**Comment by schelmo** [comment]
Because, the locale of the laravel application isnt the same anymore if you dont use the fallback with a locale that isnt translated (not existent in the database).
i added a line to the testFallback, to ensure that the laravel locale isnt changed

**Comment by vinkla** [comment]
Okay, I see your what you've fixed now. Thanks!

**Pull request merged**
