### PR TITLE
1.0

### PR DESCRIPTION
**Pull request by AlexLombry**
Send null instead of fallback locale in case of user doesn't have fallback set.

### CODE REVIEW

**Comment by vinkla** [comment]
Could you [squash your commits](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) before I merge this in.

**Comment by AlexLombry** [comment]
It's done, you can check on it

**Comment by vinkla** [comment]
Maybe you could remove the `is_null` wrap at all. Since this is an Eloquent object it will return null if its empty anyways.

**Comment by vinkla** [comment]
Great job. Merged.

**Comment by AlexLombry** [comment]
Thank you :)

**Pull request merged**
