### PR TITLE
Add new simpler translator

### PR DESCRIPTION
**Pull request by vinkla**
This is the 3.0 release for the Laravel Translator package.

Due to some great improvements in [Laravel Translatable](https://github.com/dimsav/laravel-translatable) we're going to change tracks with this translator package. We don't need two separate packages doing the same stuff. The only reason this package even exists is due to some missing functionality in the Laravel Translatable package at the time. Since then that package has matured a lot and had some great improvements. Big thanks to @dimsav for making and maintaining his [Laravel Translatable](https://github.com/dimsav/laravel-translatable) package!

For version 3.0 we are going to make things simpler. The new version will focus on getting translations up and running with as little effort as possible. No migrations, configuration files or service providers should be needed to use this package (possible? maybe). This is still in very early stages of development and we're open for new ideas and changes if someone would come up with any. Don't hesitate to leave a comment below.

What needs to be done:
- [x] Add back save
- [x] Add back update
- [x] Add better test suite
- [x] Add new and better docs
- [x] Cached translations
- [x] Remove configuration files
- [x] Remove migration files
- [x] Remove service provider

### CODE REVIEW

**Comment by dimsav** [comment]
Hey @vinkla, I wasn't aware of your package before today. It looks however that you follow a similar approach to laravel-translatable to deliver translations. 

What are the features you're missing? Make an issue or PR and maybe we could implement them :)

**Comment by vinkla** [comment]
Hey @dimsav, thanks for getting back. Yes, currently this package has a similar approach. This is why I'm taking a new approach with this package.

Back then (like a year ago) there were some missing feature in the Laravel Translatable that I really needed. I think it had to do with keeping locales in the database or something similar. Today, your package is awesome and we don't need two packages doing the exact same thing. 

If I ever find anything that I would like to see in your package I would definitely open an issue or better yet, create a pull request.

**Comment by vinkla** [comment]
Btw, do you have any tips on getting migrations and seeds spinning on Travis? I can't seem to get it right.

**Comment by dimsav** [comment]
For migrations and seeds see the database setup [here](https://github.com/dimsav/laravel-translatable/blob/master/.travis.yml). I run the migrations before each tests [here](https://github.com/dimsav/laravel-translatable/blob/master/tests/TestsBase.php#L59).

Also for simplicity I added the test seeds within a migration. See migrations [here](https://github.com/dimsav/laravel-translatable/tree/master/tests/migrations).

**Comment by alexanderweiss** [comment]
Sounds like a great idea! I don't really have any feature requests right now.

**Comment by vinkla** [comment]
@dimsav Thanks for sharing, I'll look into it!

**Comment by vinkla** [comment]
@alexanderweiss Glad you like it! Don't hesitate if you ever come up with something cool!

**Comment by schelmo** [comment]
Hi,
if i understand correctly, this change would eliminate the locales table ?
if so, it gets very difficult to delete translations if you want to delete a whole locale.
Do you have to go through every translated table and delete the localized entry ?
Or how would you achieve this ?

**Comment by vinkla** [comment]
@schelmo That is correct. You would have to go through every table.

**Pull request merged**
