### PR TITLE
Added ability to refuse the fallback translation

### PR DESCRIPTION
**Pull request by thujohn**
No breaking change
Just added a parameter to translate()

### CODE REVIEW

**Comment by vinkla** [comment]
LGTM, could you provide a use case for this?

**Comment by thujohn** [comment]
I'm building a registry package for storing values based on keys.

I have a form with : key, translations[en], translations[fr]
When I want to edit a record and a translation is missing I don't want to have any value.

This is what I'm using
```php
$term->translate($locale->language)->value
```

**Comment by vinkla** [comment]
But you still want to use the existing fallback functionality?

**Comment by thujohn** [comment]
Yes it's why I added ```$exists = true``` to keep the compatibility

**Comment by vinkla** [comment]
Okay, great. I'll merge this in.

**Comment by vinkla** [comment]
https://github.com/vinkla/translator/releases/tag/2.2.1

**Pull request merged**
